[package]
name = "gen-syscalls"
version = "0.1.0"
authors = ["Jason White <rust@jasonwhite.io"]
edition = "2018"

[dependencies]
goblin = "0.2"
libc = "0.2"
nix = "0.17"
scroll = "0.10"
serde = "1"
serde_json = "1"
structopt = "0.3"
